rules   = rule *(eor rule)
rule    = tag ":" [WSP] values
tag     = ALPHA *(ALPHA / DIGIT / "-")
values  = value [WSP] *("," [WSP] value)
value   = token / text / number / boolean / date
boolean = "true" / "false"
number  = 1*(DIGIT) *("." DIGIT) ; needs refinement. E.g. 100,000.023
token   = ALPHA *(ALPHA / DIGIT / "-" / "_")
text    = DQUOTE *(UTF8) DQUOTE
date    = 4(DIGIT) "-" 2(DIGIT) "-" 2(DIGIT)

eor     = LF / CRLF ; end of rule

UTF8    = ... ; Any UTF8 codepoint

; From https://tools.ietf.org/html/rfc5234
DQUOTE   =  %x22
ALPHA    =  %x41-5A / %x61-7A   ; A-Z / a-z
BIT      =  "0" / "1"
CR       =  %x0D ; carriage return
CRLF     =  CR LF ; Internet standard newline
DIGIT    =  %x30-39 ; 0-9
DQUOTE   =  %x22 ; " (Double Quote)

HEXDIG   =  DIGIT / "A" / "B" / "C" / "D" / "E" / "F"
HTAB     =  %x09 ; horizontal tab
LF       =  %x0A ; linefeed
SP       =  %x20
WSP      =  SP / HTAB ; white space
